# Generated by Django 6.0.2 on 2026-02-26 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('police', '0002_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='policeprofile',
            name='auth_token',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
