# Generated by Django 6.0.2 on 2026-02-26 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('police', '0003_policeprofile_auth_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='created_by_police',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='complaint',
            name='police_officer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='policeprofile',
            name='auth_token',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
