# Generated by Django 6.0.2 on 2026-02-10 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sosalert',
            name='citizen_mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='sosalert',
            name='citizen_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
