# Generated by Django 6.0.2 on 2026-02-26 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sos', '0002_sosalert_citizen_mobile_sosalert_citizen_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sosalert',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved')], default='ACTIVE', max_length=20),
        ),
    ]
